public enum EEvent
{
    /// <summary>
    /// 参数：即将加载的场景号
    /// </summary>
    BeforeLoadScene,
    /// <summary>
    /// 参数：刚加载好的场景号
    /// </summary>
    AfterLoadScene,

    GameLoadIn,

    OnUserRegister ,
     OnUserLogin ,
    OnUnLock ,
     OnStatusNotify,
    OnCharacterDetail ,
    OnSwitchCharacter ,
     OnAttrPromoteInfo ,
     OnBagHandle ,
     OnItemBuy ,
     OnCombatPowerRanking ,
     OnFollowRes ,
     OnUserStatusChange,
     OnQueryTran ,
     OnBuyTran ,
     OnHeartBeat,
     OnOfferPrice ,
     OnAuction ,
     OnGetAuctionList,
     OnTips,
     OnMyRoom ,
     OnInviteResponse ,
     OnInviteRequest ,
     OnKickOut ,
     OnRoomStartGame ,
     OnNickNameSearch,
     OnAddRoomRequest,
     OnAddRoomResponse,
     OnOutRoom ,
     OnFollowList,
     OnChat ,
     OnUserStatusQuery ,
     OnStartMatch,
     OnMatchResponse ,
     OnFrameHandle,
     OnPercentForward ,
     OnRepairFrame ,
     OnAddLiveResponse,
     OnLiveFrame,
     OnValidateOpenRoom,
     OnGameOver2,

     UIMessageBox_OnClickYes,
     UIMessageBox_OnClickNo,
     UIWindow_OnClose ,
     TabView_OnTabSelect ,
     ListView_OnItemSelected,
     UICharacterSelect_list ,
     OnCharacterDetail_UI,
     OnSwitchCharacter_UI,
     OnAttrPromoteInfo_UI,
     OnBagHandle_UI ,
     UIInputBox_OnClickYes,
     UIInputBox_OnClickNo ,
     UserCoinChange,
     OnCombatPowerRanking_UI ,
     OnFollowRes_UI ,
     CombatPowerRankingRefieshUI ,
     OnUserStatusChange_UI ,
     OnQueryTran_UI ,
     OnBuyTran_UI ,
     OnHeartBeat_UI ,
     AuctionRefreshUI,
     OnGetAuctionList_UI ,
     UIBag_OnClickSelected ,
     OnOfferPrice_UI ,
     OnAuction_UI ,
     OnMyRoom_UI ,
     OnKickOut_UI,
     OnRoomStartGame_UI,
     OnNickNameSearch_UI ,
     OnMyRoom_RefieshUI ,
     FollowListRefieshUI ,
     OnChat_UI,
     OnUserStatusQuery_UI,
     OnPrivateUserStatusChange ,
     OnChangeRedNum ,
     OnBattleGameIn ,
     OnItemBuy_UI,
     OnWorldElementExecuteOnceSuccess ,
     OnAddOptClient ,
     OnEnterGameProcess,

}
